# -*- coding: utf-8 -*-
"""DVA lab_1,2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AhC8ry5KDzvulr7b0E5WUZyOIlgG3r0r
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn import datasets
import numpy as np

data = datasets.load_iris()
data = pd.DataFrame(data.data, columns=data.feature_names)
data.head()

plt.scatter(data['sepal length (cm)'], data['sepal width (cm)'])

"""# Lab 1 (25-09-2024)"""

# Line plot
data = pd.read_csv('sales.csv', index_col = 'day')
data.head()s

"""Line chart"""

plt.plot(data.index,data['week 1'])
plt.title('Sales of week 1')
plt.xlabel('Day')
plt.ylabel('Sales (in rupees)')
plt.show()

plt.plot(data.index,data['week 2'])
plt.title('Sales of week 2')
plt.xlabel('Day')
plt.ylabel('Sales (in rupees)')
plt.show()


plt.plot(data.index,data['week 3'])
plt.title('Sales of week 3')
plt.xlabel('Day')
plt.ylabel('Sales (in rupees)')
plt.show()

"""Bar chart"""

f, ax = plt.subplots()
plt.figure(figsize=(14, 7))
plt.subplot(1,3,1)
ax.bar(data.index, data['week 1'], color ='blue')

plt.subplot(1,3,2)
ax.bar(data.index, data['week 2'], color ='orange')

plt.subplot(1,3,3)
ax.bar(data.index, data['week 3'], color ='green')

data.set_index('day').plot(kind ='bar', width = 0.5)

plt.hist(list(data['week 1']), list(data['week 1']), data['week 1'], 7, density = True, color = ['b','r','y'])

"""2."""

h = pd.DataFrame([60, 61, 63, 65, 61, 60])
w = pd.DataFrame([47, 89, 52, 58, 50, 47])
plt.figure(figsize=(14, 7))

plt.subplot(1,2,1)
plt.hist(h)

plt.subplot(1,2,2)
plt.hist(w,color='y')

"""Lab 2 (09-10-2024)

Games data set (02)
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('game.csv', index_col='game')
data

# 1. Line plot
plt.plot(data.index, data['points'], marker='o')
plt.title('Points scored by each game')
plt.xlabel('Game')
plt.ylabel('Points over the season')
plt.show()

# 2
plt.bar(data.index, data['att'])
plt.title('Attendance throughout the season')
plt.xlabel('Game')
plt.ylabel('Attendance')
plt.show()

print("\nAverage attendance=", data['att'].mean())

# 4
r = ['70-80', '81-90', '91-100', '100-110']
f =[1,1,2,2]

# Create the bar chart
plt.bar(r, f, color='skyblue')
plt.title('Points scored at each game')
plt.xlabel('Range')
plt.ylabel('Frequency')
plt.show()

# 5. bar chart showing points schored against each opponent

plt.bar(data.index,data['points'])
plt.title('Points scored against each opponent')
plt.xlabel('Opponent')
plt.ylabel('Points')
plt.show()

# 6. Bar chart - visualise attendance based on different opponents

# 7. Bar chart - visualise attendance based on any attribute

"""Match dataset (03)

```
# This is formatted as code
```


"""

d = pd.read_csv('matches.csv', index_col='match')
d

# 1.
plt.bar(d['home team'],d['home goals']+d['away goals'])
plt.title('Goals scored by each team')
plt.xlabel('Team')
plt.ylabel('Goals')
plt.show()

#
plt.bar(d.index, d['att'])
plt.title('Attendance throughout the season')
plt.xlabel('Match')
plt.ylabel('Attendance')
plt.show()

plt.bar(d['home team'],d['home goals'])