# -*- coding: utf-8 -*-
"""DVA_lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLbZL2BH_GFkXIXHk0OLA7aA5TmFJ0Ll

# Lab 3
23-10-2024

Use a dataset with missing values. apply mean, median and mode imputation to handle the missing data. The create pair plot using seaborn befor and after im putation. How do the relationships between features change after each imputation method?

Use box plots to comapr the spread of a key feature before and adter handling missing values. Which imputation technique best preserves the original distrbution and why?
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('Diabetes Missing Data.csv')
df.head()

# before imputation
sns.pairplot(df)

df['Skin_Fold'] = df['Skin_Fold'].fillna(df['Skin_Fold'].mean())
df['Serum_Insulin'] = df['Serum_Insulin'].fillna(df['Serum_Insulin'].mean())
df['Diastolic_BP'] = df['Diastolic_BP'].fillna(df['Diastolic_BP'].mean())
df.head()

# after imputation
sns.pairplot(df)

df['Skin_Fold'] = df['Skin_Fold'].fillna(df['Skin_Fold'].median())
df['Serum_Insulin'] = df['Serum_Insulin'].fillna(df['Serum_Insulin'].median())
df['Diastolic_BP'] = df['Diastolic_BP'].fillna(df['Diastolic_BP'].median())
df.head()

df['Skin_Fold'] = df['Skin_Fold'].fillna(df['Skin_Fold'].mode()[0])
df['Serum_Insulin'] = df['Serum_Insulin'].fillna(df['Serum_Insulin'].mode()[0])
df['Diastolic_BP'] = df['Diastolic_BP'].fillna(df['Diastolic_BP'].mode()[0])
df.head()

sns.boxplot(data = df)

sns.boxplot(data = df, x='Age', y='Glucose')

sns.boxplot(data = df, x='Age', y='BMI')